In [2]:
import numpy as np
import pandas as pd

# Pandas and Numpy Introduction

Finished through the introduction to Python, logic, and programming! Now, we're getting into the Pandas and Numpy package world.

## Numpy and Pandas

Numpy and Pandas are the two biggest packages out there for data science.

### Numpy Arrays

In [1]:
list1 = [1,2,3,4]

In [3]:
array1 = np.array(list1)
print(array1)

[1 2 3 4]


Somtimes we want a two dimensional array:

In [4]:
list2 = [[1,2,3], [4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


NumPy makes it easy to perform all kinds of operations on these arrays:

In [5]:
toyPrices = np.array([5,8,3,6])
print(toyPrices - 2)

[3 6 1 4]


### Pandas `series`

This is a data structure that is commonly used in Pandas and has some special considerations found at [the API reference](https://pandas.pydata.org/docs/reference/api/pandas.Series.html).

In [6]:
# Create a Series using a NumPy array of ages with the default numerical indices
ages = np.array([13,25,19])
series1 = pd.Series(ages)
print(series1)

0    13
1    25
2    19
dtype: int64
