In [5]:
import numpy as np
import pandas as pd

# Pandas and Numpy Introduction

Finished through the introduction to Python, logic, and programming! Now, we're getting into the Pandas and Numpy package world.

## Numpy and Pandas

Numpy and Pandas are the two biggest packages out there for data science.

### Numpy Arrays

In [6]:
list1 = [1,2,3,4]

In [7]:
array1 = np.array(list1)
print(array1)

[1 2 3 4]


Somtimes we want a two dimensional array:

In [8]:
list2 = [[1,2,3], [4,5,6]]
array2 = np.array(list2)
print(array2)

[[1 2 3]
 [4 5 6]]


NumPy makes it easy to perform all kinds of operations on these arrays:

In [9]:
toyPrices = np.array([5,8,3,6])
print(toyPrices - 2)

[3 6 1 4]


### Pandas `series`

This is a data structure that is commonly used in Pandas and has some special considerations found at [the API reference](https://pandas.pydata.org/docs/reference/api/pandas.Series.html).

In [10]:
# Create a Series using a NumPy array of ages with the default numerical indices
ages = np.array([13,25,19])
series1 = pd.Series(ages)
print(series1)

0    13
1    25
2    19
dtype: int64


In [11]:
# Create a Series using a NumPy array of ages but customize the indices to be the names that correspond to each age
ages = np.array([13,25,19])
series1 = pd.Series(ages,index=['Emma', 'Swetha', 'Serajh'])
print(series1)

Emma      13
Swetha    25
Serajh    19
dtype: int64


### Pandas `DataFrame`

From Codeacademy:

> Another important type of object in the pandas library is the DataFrame. This object is similar in form to a matrix as it consists of rows and columns. Both rows and columns can be indexed with integers or String names. One DataFrame can contain many different types of data types, but within a column, everything has to be the same data type. A column of a DataFrame is essentially a Series. All columns must have the same number of elements (rows).

The really key part here: we can make the `dataframe` from all kinds of sources. Most likely, I would be dealing with CSVs and SQL-like databases.

In [ ]:
dataf = pd.DataFrame([
    ['John Smith','123 Main St',34],
    ['Jane Doe', '456 Maple Ave',28],
    ['Joe Schmo', '789 Broadway',51]
    ],
    columns=['name','address','age'])

In [13]:
print(dataf)

         name        address  age
0  John Smith    123 Main St   34
1    Jane Doe  456 Maple Ave   28
2   Joe Schmo   789 Broadway   51


In [16]:
dataf.set_index('name')

address  age
name                          
John Smith    123 Main St   34
Jane Doe    456 Maple Ave   28
Joe Schmo    789 Broadway   51

In [17]:
dataf.set_index('age')

name        address
age                           
34   John Smith    123 Main St
28     Jane Doe  456 Maple Ave
51    Joe Schmo   789 Broadway

## Resource

A great resource for checking out some interesting parts of [pandas](https://pandas.pydata.org/docs/user_guide/10min.html).